// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $BleConnectionIsland from "./islands/BleConnectionIsland.tsx";
import * as $ChartIsland from "./islands/ChartIsland.tsx";
import * as $SensorCalibrationIsland from "./islands/SensorCalibrationIsland.tsx";
import * as $SensorDataDisplayIsland from "./islands/SensorDataDisplayIsland.tsx";
import * as $StageIsland from "./islands/StageIsland.tsx";
import * as $StageNavigatorIsland from "./islands/StageNavigatorIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BleConnectionIsland.tsx": $BleConnectionIsland,
    "./islands/ChartIsland.tsx": $ChartIsland,
    "./islands/SensorCalibrationIsland.tsx": $SensorCalibrationIsland,
    "./islands/SensorDataDisplayIsland.tsx": $SensorDataDisplayIsland,
    "./islands/StageIsland.tsx": $StageIsland,
    "./islands/StageNavigatorIsland.tsx": $StageNavigatorIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
