// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $BluetoothDisconnectedNotificationIsland from "./islands/BluetoothDisconnectedNotificationIsland.tsx";
import * as $BluetoothSetupIsland from "./islands/BluetoothSetupIsland.tsx";
import * as $ChartIsland from "./islands/ChartIsland.tsx";
import * as $NavigationNotificationIsland from "./islands/NavigationNotificationIsland.tsx";
import * as $NextTransitionIsland from "./islands/NextTransitionIsland.tsx";
import * as $PreviousTransitionIsland from "./islands/PreviousTransitionIsland.tsx";
import * as $SensorSetupIsland from "./islands/SensorSetupIsland.tsx";
import * as $StageIsland from "./islands/StageIsland.tsx";
import * as $TrainingIsland from "./islands/TrainingIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BluetoothDisconnectedNotificationIsland.tsx":
      $BluetoothDisconnectedNotificationIsland,
    "./islands/BluetoothSetupIsland.tsx": $BluetoothSetupIsland,
    "./islands/ChartIsland.tsx": $ChartIsland,
    "./islands/NavigationNotificationIsland.tsx": $NavigationNotificationIsland,
    "./islands/NextTransitionIsland.tsx": $NextTransitionIsland,
    "./islands/PreviousTransitionIsland.tsx": $PreviousTransitionIsland,
    "./islands/SensorSetupIsland.tsx": $SensorSetupIsland,
    "./islands/StageIsland.tsx": $StageIsland,
    "./islands/TrainingIsland.tsx": $TrainingIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
